### ISSUE TITLE
Some plugins are incorrectly attributed.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/docs#13]
Bloom, Excel and JPEGXL plugins are all attributed to Redox (me) even though they are all by aTom3333. Their links are correct however the text is incorrect.
![image](https://user-images.githubusercontent.com/42661490/140597620-29bae90b-5d71-40d0-8228-33cf0e010aa6.png)

**Comment by jackjt8** [comment]
Fixed via f16d8bcb560d999bfef6bfdd19af5d9082aaf7bb
