### ISSUE TITLE
Rework Reference - Introduction

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/docs#55]
The `Introduction` article requires further refinement.

- [ ] #68
- [x] Samples Per Pixel (SPP) - Update gif with a smoother animation with more frames
- [x] Merge NEE/ESS stuff together
- [x] Emitter Sampling Strategy (ESS) - Section is confusing. Probably needs diagrams to explain the complex nature of ESS.
- [x] Materials - Need to add a section on various material properties and how they function (in context). This is intended to replace some of the content within `Reference - Render Controls - Materials` as that article should just be for the UI and short descriptions.
- [x] Image formats and color - This section does not really fit here. Maybe we should move some of the content to `Reference - Scene Format` and other parts to `Reference - Render Controls - Advanced`.

---

Given the scope of the article, and the changes that may be required, I would not be against the sub-division of the article. Please use this issue to further expand on any issues with the article and your suggestions.

**Comment by Peregrine05** [comment]
As to the subdivision of the article: What about placing "Path Tracing", "Random Sampling", and "Renderers" together into one article; "Samples Per Pixel (SPP)", "Render Time", "More about Noise", and "SPP Comparisons together into one article; "Emitter Sampling Strategy (ESS) gets its own article; "Data Structures" gets its own article; and "Image formats and color" gets moved elsewhere?

**Comment by jackjt8** [comment]
So effectively we would have; and this list of headings is subject to change/expansion:

`Introduction`:
- `Path Tracing`
- `Random Sampling`
- `Renderers`

"More on Noise":
- `Samples Per Pixel (SPP)`
- `Render Time`
- `More about Noise`
- `SPP Comparisons`

Next Event Estimation:
- "Small intro and bit on sun sampling"
- `Emitter Sampling Strategy (ESS)`

---

`Image formats and color` move is already noted in final bullet point at the time of writing.

> * [ ]  Image formats and color - This section does not really fit here. Maybe we should move some of the content to `Reference - Scene Format` and other parts to `Reference - Render Controls - Advanced`.

---

`Data Structures` is a bit tricky. So yes, we do actually have some information within  `Reference > Scene Format` and we could certainly expand it a bit more however, that is a technical document. Given the importance of BVHs and Octrees both within Chunky and with other applications at the very least we would need to slot an article in between `Introduction` and "More on Noise". Though I would argue that it's probably more important to keep it together with our `Introduction`.

**Comment by Peregrine05** [comment]
This is what I have so far:

`Introduction`
- "Path Tracing"
- "Random Sampling"
- "Renderers"
`Samples Per Pixel (SPP) and Noise`
- "Samples Per Pixel (SPP)" (Expand this section and move the part about Sun NEE into `Emitter Sampling Strategy (ESS)`)
- "More About Noise"
- "SPP Comparisons"
- "Render Time"
`Emitter Sampling Strategy (ESS)` (Maybe rename this to "Next Event Estimation (NEE)")
`Data Structures`
> Maybe move `Denoising` down with `Headless`, `Scene Format`, `Skymaps`, etc.
`User Interface`

The first paragraph in `Image Formats and Color` can be moved to the `Scene Format` article, and the details about the file formats could be moved to the Advanced tab article.

**Comment by jackjt8** [comment]
I am mostly happy with the proposed changes. Moving `Denoising` down with `Headless`, etc. is a good idea.

I am still not certain on having `Data Structures` as a standalone article given the overlap with `Scene Format`. I would still prefer if it would be contained within either `Introduction` or `Samples Per Pixel (SPP) and Noise` given it's close relation to both of these topics.

**Comment by Peregrine05** [comment]
I was thinking of the logical progression of the topics. First is the Chunky renderer and path tracing. That leads into SPP and noise. And then it goes into other rendering strategies, such as NEE. I agree with keeping how Chunky stores world data with the rest of how Chunky works, but merging that section into the previous sections somewhat breaks the order of topics. That's why, for now, I have it after the ESS page. But it would probably fit best in the Path Tracing article if it is to be merged.

**Comment by jackjt8** [comment]
I'll try and figure out how to rework the article at a later date for it's remerge among some of the other improvements.

**Comment by jackjt8** [comment]
```
Introduction
	Path Tracing - Shorten Data Structures link to `Scene Format` for in depth
	Samples and Noise
	Next Event Estimation - Sun NEE + (Improved) ESS
	Materials?
User Interface
Render Controls
	... - Expand image formats
Denoising - Moved here
Headless
Scene Format - Expand Octree, BVH, and image format/internal stuff
Skymaps
Theming
```

Updated*

**Comment by Peregrine05** [comment]
Task 2 of 6 complete:
The main SPP comparison animation.
![x2_2-sec_loop](https://user-images.githubusercontent.com/92183530/164559055-833eb060-c164-4e78-a612-98d8be7a3123.gif)
Compare 1k and 2k SPP
![1ki-2ki_2-sec_loop](https://user-images.githubusercontent.com/92183530/164559678-63a477fe-a22a-47db-86f2-36fc1906dc43.gif)
Compare 20k and 21k SPP
![20k-21k_2-sec_loop](https://user-images.githubusercontent.com/92183530/164559706-4f005a5a-8643-4b43-9ab3-d592aa40566a.gif)
