### ISSUE TITLE
Low site security score

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/docs#60]
[Mozilla Observatory summary](https://observatory.mozilla.org/analyze/chunky-dev.github.io)

While we likely do not need to improve site security given the nature of the content we are hosting it may still be a fun project for someone to undertake.

**Comment by leMaik** [comment]
I'd rather not customize a page without any dynamic content or user data input and keep the MkDocs template as is.

**Comment by jackjt8** [comment]
No problem. I thought as much
