### ISSUE TITLE
TODO - Subsections, headings, and readability improvements

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/docs#82]
- The `Controls` headers used across `User Interface` can be considered redundant and unnecessary. It also increases depth for no real reason or benefit.
- Suggest renaming `2.5.0 controls` to `Upcoming Changes`. At least until we figure out multi-versioning of some description.
- Longer pages, like `Render Controls - Camera`, should make more use of subsections with headers to further aid navigation around the page. for example `presets & camera selection(?)`, `position & orientation`, `projection`, `depth of field/focusing`.
- We should remove/reduce line breaks, ie `---` as they do look a bit messy. These exist throughout the docs so a careful comb is required.
- "The Postprocessing tab, which is the eighth tab in the left control panel," - Given the order and number of tabs changes often we probably shouldn't number them. As long as we are clear on the names of the tab this will reduce work.

**Comment by Peregrine05** [comment]
- I agree that the `Controls` headers are unnecessary, as the page is dedicated to controls.
- I'm currently working on separating the docs per Chunky release channel. There will be no `2.5.0 Snapshot controls` section in each page.
- As to removing page separators, how about only using them to separate dialog box controls from the rest of the page?

**Comment by jackjt8** [comment]
Page separators for dialogue boxes may be fine. We will need to evaluate how it looks.
