### ISSUE TITLE
Find a better way to number figures

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/docs#84]
A temporary solution would probably be to simply number the figures per-page. E.G., For each page, there is Figure 1, Figure 2, Figure 3, etc. References to figures in other pages would still work; they would just be, "see [this image]()" for...

**Comment by jackjt8** [comment]
Re: #72 

> Pheasant can automatically number headers, figures, tables, etc.


I agree that figures should be numbered per-page. We may wish to automate this and Pheasant should be able to do it.. though whether or not we want an extensive plugin for one feature...
