### ISSUE TITLE
Navigation links at the bottom of the page can point to excluded pages

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/docs#86]
Issue with #85

When docs are built for a particular Chunky version, pages that are excluded from the build are not shown in the nav. However, when the page that was excluded is the previous or next page, the `Next`/`Previous` button at the bottom of the page still points to that excluded page, and clicking that button leads to a 404 error.

An example at the time of this writing is this page: https://chunky-dev-docs-pr-85.surge.sh/docs/reference/user_interface/chunky_gui/

Click the `Next` button at the bottom of the page to reproduce the issue.

**Comment by Peregrine05** [comment]
A temporary solution (proposed by leMaik) could be to disable the navigation links until a proper solution presents itself. While not ideal, the docs do remain fully navigable.

**Comment by leMaik** [comment]
Fixed it the proper way:
![image](https://user-images.githubusercontent.com/5544859/224578831-c5730491-2a01-4293-a8ac-b4fb75710797.png)
