### ISSUE TITLE
Update installation docs to include the JavaFX installer

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/docs#87]
With the merge of https://github.com/chunky-dev/chunky/pull/1292, the installation just got one step easier. We should probably mention that and move the manual JavaFX installation into troubleshooting.

**Comment by ThatRedox** [comment]
Here is a screenshot of the installer dialog:
![image](https://user-images.githubusercontent.com/42661490/212439050-9eddc848-cd40-475d-a9d2-b0f7c09e290b.png)

The first link (`JavaFX is licensed under...`) links to the gluon page.
The second link links to `https://chunky-dev.github.io/docs/getting_started/installing_chunky/#setup`.
