### ISSUE TITLE
Add more internal links

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/docs#91]
Need to link [Lighting: ESS](https://chunky-dev.github.io/docs/snapshot/reference/user_interface/chunky/render_controls/lighting/#emitter-controls) To [Intro: Emitter Sampling Strategy (ESS)](https://chunky-dev.github.io/docs/user_guides/introduction/next_event_estimation/#emitter-sampling-strategy-ess)

- Opposed to flooding the UI reference pages with too much information we should link back to the Intro pages to expand on things. Feel free to suggest other links that may be required on this issue.

**Comment by Peregrine05** [comment]
This already links back to Intro: Emitter Sampling Strategy (ESS).
![image](https://github.com/chunky-dev/docs/assets/92183530/1ce4f3ac-e671-41d8-a817-f25e44adb36b)
